export default {
  "debug":true,
  "agreements":{
    "serviceUrl": "https://uniapp.dcloud.io/", // 用户服务协议链接
    "privacyUrl": "https://uniapp.dcloud.io/", // 隐私政策条款链接
    /*
    * 哪些场景下显示
    * 1. register注册（包括登录并注册，如：短信验证码登录，一键登录）
    * 2. login登录（如：用户名密码登录，短信验证码登录）
    */
    "scopeList": [
      "register","login","realNameVerify","univerify"
    ]
  },
  "loginTypes":[
    "username",
    // #ifdef APP && uniVersion >= 3.98
    "univerify",
    // #endif
    "smsCode",
    // 以下登录方式 uni-app x 暂不支持
    /*
      "qq",
      "xiaomi",
      "sinaweibo",
      "taobao",
      "facebook",
      "google",
      "alipay",
      "douyin",
      "weixin",
      // #ifdef APP
      "univerify",
      "apple"
      // #endif
    */
  ],
  /**
   * 密码强度
   * super（超强：密码必须包含大小写字母、数字和特殊符号，长度范围：8-16位之间）
   * strong（强: 密密码必须包含字母、数字和特殊符号，长度范围：8-16位之间）
   * medium (中：密码必须为字母、数字和特殊符号任意两种的组合，长度范围：8-16位之间)
   * weak（弱：密码必须包含字母和数字，长度范围：6-16位之间）
   * 为空或false则不验证密码强度
   */
  passwordStrength: 'weak'
} as UTSJSONObject
