import config from '@/uni_modules/uni-id-pages-x/config.uts';
type Services = {
  id : string,
  text : string,
  logo : string
}

let servicesList = [{
  "id": "username",
  "text": "账号登录",
  "logo": "/uni_modules/uni-id-pages-x/static/login/uni-fab-login/user.png",
},
{
  "id": "smsCode",
  "text": "短信验证码",
  "logo": "/uni_modules/uni-id-pages-x/static/login/uni-fab-login/sms.png",
},
{
  "id": "weixin",
  "text": "微信登录",
  "logo": "/uni_modules/uni-id-pages-x/static/login/uni-fab-login/weixin.png",
},
{
  "id": "weixinMobile",
  "text": "微信手机号",
  "logo": "/uni_modules/uni-id-pages-x/static/login/uni-fab-login/weixin.png",
},
// #ifndef MP-WEIXIN
{
  "id": "apple",
  "text": "苹果登录",
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/apple.png",
},
{
  "id": "univerify",
  "text": "一键登录",
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/univerify.png",
},
{
  "id": "taobao",
  "text": "淘宝登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/taobao.png",
},
{
  "id": "facebook",
  "text": "脸书登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/facebook.png",
},
{
  "id": "alipay",
  "text": "支付宝登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/alipay.png",
},
{
  "id": "qq",
  "text": "QQ登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/qq.png",
},
{
  "id": "google",
  "text": "谷歌登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/google.png",
},
{
  "id": "douyin",
  "text": "抖音登录", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/douyin.png",
},
{
  "id": "sinaweibo",
  "text": "新浪微博", //暂未提供该登录方式的接口示例
  "logo": "/uni_modules/uni-id-pages-x/static/app/uni-fab-login/sinaweibo.png",
}
  // #endif
] as Services[]


const loginTypes = config.getArray<string>('loginTypes')
servicesList = servicesList.filter((item) : boolean => {
  // #ifndef APP
  //非app端去掉apple登录
  if (item.id == 'apple') {
    return false
  }
  // #endif

  // #ifdef APP
  //去掉非ios系统上的apple登录
  if (item.id == 'apple' && uni.getSystemInfoSync().osName != 'ios') {
    return false
  }
  // #endif

  // 必须是配置了的
  return loginTypes!.includes(item.id)
})


export {servicesList,Services}

