export type VibrateShortType = "heavy" | "medium" | "light"

export type VibrateShortSuccess = {
  errMsg : string
}

export type VibrateLongSuccess = {
  errMsg : string
}

export type VibrateErrorCode = 9001001 | 9001002 | 9001003

export interface VibrateFail extends IUniError {
  errCode : VibrateErrorCode
}

type VibrateShortSuccessCallback = (result : VibrateShortSuccess) => void
type VibrateLongSuccessCallback = (result : VibrateLongSuccess) => void
type VibrateFailCallback = (result : VibrateFail) => void
type VibrateComplete = any
type VibrateCompleteCallback = (result : VibrateComplete) => void

export type VibrateShortOptions = {
  type : VibrateShortType,
  success ?: VibrateShortSuccessCallback,
  fail ?: VibrateFailCallback,
  complete ?: VibrateCompleteCallback
}

export type VibrateLongOptions = {
  success ?: VibrateLongSuccessCallback,
  fail ?: VibrateFailCallback,
  complete ?: VibrateCompleteCallback
}

export type VibrateShort = (options : VibrateShortOptions) => void
export type VibrateLong = (options : VibrateLongOptions) => void

export interface Uni {
  /**
   * 使设备发生较短时间的振动。
   *
   * @uniPlatform {
   *   "app": {
   *     "android": {
   *       "osVer": "5.0",
   *       "uniVer": "√",
   *       "unixVer": "5.08"
   *     },
   *     "ios": {
   *       "osVer": "12.0",
   *       "uniVer": "√",
   *       "unixVer": "5.08"
   *     },
   *     "harmony": {
   *       "osVer": "3.0",
   *       "uniVer": "x",
   *       "unixVer": "5.08"
   *     }
   *   }
   * }
   */
  vibrateShort(options : VibrateShortOptions) : void
  /**
   * 使设备发生较长时间的振动。
   *
   * @uniPlatform {
   *   "app": {
   *     "android": {
   *       "osVer": "5.0",
   *       "uniVer": "√",
   *       "unixVer": "5.08"
   *     },
   *     "ios": {
   *       "osVer": "12.0",
   *       "uniVer": "√",
   *       "unixVer": "5.08"
   *     },
   *     "harmony": {
   *       "osVer": "3.0",
   *       "uniVer": "x",
   *       "unixVer": "5.08"
   *     }
   *   }
   * }
   */
  vibrateLong(options : VibrateLongOptions) : void
}